/* Edita aquí los proyectos. Los archivos se guardan en assets/projects y assets/videos. */
window.DESRUPTIVO_PROJECTS = [
  {id:'mcdonalds',name:"McDonald's México",category:'design',label:'DISEÑO / SOCIAL',cover:'assets/projects/mcdonalds-semaforo.jpg',tone:'mcdonalds',description:'Dos piezas para redes sociales: papas, un semáforo y una primavera llena de tipografía. Diseño con el producto al centro.',media:[{src:'assets/projects/mcdonalds-semaforo.jpg',alt:"Papas y semáforo, pieza para McDonald's México"},{src:'assets/projects/mcdonalds-primavera-story.jpg',alt:"Story de primavera para McDonald's México"}]},
  {id:'boro',name:'Boro',category:'design',label:'DISEÑO / GASTRONOMÍA',cover:'assets/projects/boro-tipografia.jpg',tone:'boro',description:'Sabor que también entra por los ojos. Cartel tipográfico y pieza de producto para la comunicación de Boro.',media:[{src:'assets/projects/boro-tipografia.jpg',alt:'Cartel tipográfico con un cono de helado Boro'},{src:'assets/projects/boro-conos.jpg',alt:'Dos conos de helado Boro'}]},
  {id:'archipielago',name:'Archipiélago',category:'design',label:'DISEÑO / INMOBILIARIO',cover:'assets/projects/pajaro-en-piedra.jpg',tone:'archipielago',description:'Pájaro en Piedra. Una pieza de comunicación inmobiliaria que combina arquitectura, entorno y una invitación a encontrar tu nido.',media:[{src:'assets/projects/pajaro-en-piedra.jpg',alt:'Pájaro en Piedra, campaña inmobiliaria para Archipiélago'}]},
  {id:'bajel',name:'Bajel',category:'design',label:'DISEÑO / GASTRONOMÍA',cover:'assets/projects/bajel-chef-story.jpg',tone:'bajel',description:'Una invitación a la mesa. Story para una cena con el chef invitado Mario Papa, con una dirección visual centrada en la experiencia gastronómica.',media:[{src:'assets/projects/bajel-chef-story.jpg',alt:'Story de cena con el chef Mario Papa en Bajel'}]},
  {id:'archipielago-video',name:'Archipiélago en movimiento',category:'video',label:'VIDEO / INMOBILIARIO',cover:'assets/videos/archipielago-indispensables-poster.jpg',tone:'video',description:'Una pieza audiovisual de Archipiélago para descubrir el entorno y sus posibilidades.',media:[{src:'assets/videos/archipielago-indispensables.mp4',type:'video',poster:'assets/videos/archipielago-indispensables-poster.jpg',alt:'Video Archipiélago: indispensables'}]},
  {id:'cosmicos',name:'Cósmicos Pet Bakery',category:'design',label:'DISEÑO / PRODUCTO',cover:'assets/projects/cosmicos-goat-milk.jpg',tone:'cosmicos',description:'Goat Milk Bears. Producto, color y composición para una pieza de comunicación de Cósmicos Pet Bakery.',media:[{src:'assets/projects/cosmicos-goat-milk.jpg',alt:'Goat Milk Bears de Cósmicos Pet Bakery'}]},
  {id:'levels',name:'Levels Dermatology',category:'design',label:'DISEÑO / SKINCARE',cover:'assets/projects/levels-murad.jpg',tone:'levels',description:'Una pieza de producto para presentar Murad Clarifying Booster en la comunicación de Levels Dermatology.',media:[{src:'assets/projects/levels-murad.jpg',alt:'Murad Clarifying Booster para Levels Dermatology'}]},
  {id:'citron',name:'Citrón · Grupo Gia',category:'design',label:'DISEÑO / CAMPAÑA',cover:'assets/projects/citron-grupo-gia.jpg',tone:'citron',description:'Comunicación visual para Citrón de Grupo Gia: una pieza sobre inversión en limón persa y vida en contacto con la naturaleza.',media:[{src:'assets/projects/citron-grupo-gia.jpg',alt:'Pieza de inversión en limón persa para Citrón de Grupo Gia'}]},
  {id:'picking',name:'Picking Express',category:'design',label:'DISEÑO / SERVICIOS',cover:'assets/projects/picking-express-embalaje.jpg',tone:'picking',description:'Una pieza que pone el servicio a la vista: embalaje personalizado para la comunicación de Picking Express.',media:[{src:'assets/projects/picking-express-embalaje.jpg',alt:'Pieza de embalaje personalizado para Picking Express'}]},
  {id:'alavar',name:'A Lavar',category:'video',label:'VIDEO / COMERCIAL',cover:'assets/videos/a-lavar-sucursal-poster.jpg',tone:'video',description:'Una pieza audiovisual para presentar una sucursal de A Lavar.',media:[{src:'assets/videos/a-lavar-sucursal.mp4',type:'video',poster:'assets/videos/a-lavar-sucursal-poster.jpg',alt:'Video de sucursal A Lavar'}]},
  {id:'mitica',name:'Mítica · Promocional',category:'video',label:'VIDEO / PROMOCIONAL',cover:'assets/videos/mitica-promocional-poster.jpg',tone:'video',description:'Pieza promocional audiovisual del archivo de trabajo de Desruptivo.',media:[{src:'assets/videos/mitica-promocional.mp4',type:'video',poster:'assets/videos/mitica-promocional-poster.jpg',alt:'Video promocional Mítica'}]},
  {id:'recorrido',name:'Recorrido residencial',category:'video',label:'VIDEO / RECORRIDO',cover:'assets/videos/recorrido-residencial-poster.jpg',tone:'video',description:'Un recorrido residencial en formato vertical: espacio, presentación y movimiento.',media:[{src:'assets/videos/recorrido-residencial.mp4',type:'video',poster:'assets/videos/recorrido-residencial-poster.jpg',alt:'Video de recorrido residencial'}]},
  {id:'cuatro-millones',name:'Cuatro millones',category:'video',label:'VIDEO / INMOBILIARIO',cover:'assets/videos/cuatro-millones-poster.jpg',tone:'video',description:'Contenido inmobiliario en formato vertical, con presentación a cámara.',media:[{src:'assets/videos/cuatro-millones.mp4',type:'video',poster:'assets/videos/cuatro-millones-poster.jpg',alt:'Video inmobiliario Cuatro millones'}]}
];
