/* Edita aquí los proyectos. Los archivos se guardan en assets/projects y assets/videos. */
window.DESRUPTIVO_PROJECTS = [
  {id:'mcdonalds',name:"McDonald's México",category:'design',label:'DISEÑO / SOCIAL',cover:'assets/projects/mcdonalds-semaforo.jpg',tone:'mcdonalds',description:'Tres piezas para redes sociales: papas que se entretejen con la tipografía, un semáforo y una primavera llena de color. Diseño con el producto al centro.',media:[{src:'assets/projects/mcdonalds-semaforo.jpg',alt:"Papas y semáforo, pieza para McDonald's México"},{src:'assets/projects/mcdonalds-papitas.jpg',alt:"La vida es mejor con papitas, pieza para McDonald's México"},{src:'assets/projects/mcdonalds-primavera-story.jpg',alt:"Story de primavera para McDonald's México"}]},
  {id:'selvadentro',name:'Selvadentro',category:'design',label:'DISEÑO / INMOBILIARIO',cover:'assets/projects/selvadentro-amenidades.jpg',tone:'selvadentro',description:'Lotes residenciales en Tulum. Una serie para redes que cuenta el lugar a través de su entorno: cenotes, playa, zona arqueológica y amenidades entre la selva.',media:[{src:'assets/projects/selvadentro-amenidades.jpg',alt:'Amenidades de Selvadentro entre la selva de Tulum'},{src:'assets/projects/selvadentro-cenotes-playa.jpg',alt:'Cenote subterráneo, pieza Cenotes + Playa de Selvadentro'},{src:'assets/projects/selvadentro-playa-cenotes.jpg',alt:'Playa de Tulum, pieza Playa + Cenotes de Selvadentro'},{src:'assets/projects/selvadentro-tulum.jpg',alt:'Zona arqueológica frente al mar, lotes residenciales Selvadentro en Tulum'}]},
  {id:'boro',name:'Boro',category:'design',label:'DISEÑO / GASTRONOMÍA',cover:'assets/projects/boro-tipografia.jpg',tone:'boro',description:'Sabor que también entra por los ojos. Cartel tipográfico y pieza de producto para la comunicación de Boro.',media:[{src:'assets/projects/boro-tipografia.jpg',alt:'Cartel tipográfico con un cono de helado Boro'},{src:'assets/projects/boro-conos.jpg',alt:'Dos conos de helado Boro'}]},
  {id:'cosmicos',name:'Cósmicos Pet Bakery',category:'design',label:'DISEÑO / PRODUCTO',cover:'assets/projects/cosmicos-goat-milk.jpg',tone:'cosmicos',description:'Una pet bakery con personalidad pop. Posts y stories con producto, color y composición: lanzamientos, recetas, temporada de otoño y hasta una colección para humanos.',media:[{src:'assets/projects/cosmicos-goat-milk.jpg',alt:'Goat Milk Bears de Cósmicos Pet Bakery'},{src:'assets/projects/cosmicos-treats-love.jpg',alt:'Dos perros en un sillón rosa con premios de Cósmicos'},{src:'assets/projects/cosmicos-beef-liver.jpg',alt:'Lanzamiento de Beef Liver Sprinkles de Cósmicos'},{src:'assets/projects/cosmicos-pawgarita.jpg',alt:'Receta Pawgarita con Beef Liver Sprinkles de Cósmicos'},{src:'assets/projects/cosmicos-pupkin-spice.jpg',alt:'Galleta Pupkin Spice Latte de la temporada de otoño de Cósmicos'},{src:'assets/projects/cosmicos-coleccion-humanos.jpg',alt:'Nueva colección de ropa para humanos de Cósmicos'}]},
  {id:'sacala',name:'Sacalá',category:'design',label:'DISEÑO / INMOBILIARIO',cover:'assets/projects/sacala-hacienda.jpg',tone:'sacala',description:'Inversión en Izamal, Yucatán. Tipografía serif sobre el paisaje: una hacienda que habla de naturaleza y exclusividad, y la selva vista desde arriba.',media:[{src:'assets/projects/sacala-hacienda.jpg',alt:'Hacienda en Izamal, pieza de bienvenida de Sacalá'},{src:'assets/projects/sacala-selva.jpg',alt:'Selva de Yucatán vista desde arriba, pieza de inversión de Sacalá'}]},
  {id:'archipielago',name:'Archipiélago',category:'design',label:'DISEÑO / INMOBILIARIO',cover:'assets/projects/pajaro-en-piedra.jpg',tone:'archipielago',description:'Pájaro en Piedra. Una pieza de comunicación inmobiliaria que combina arquitectura, entorno y una invitación a encontrar tu nido.',media:[{src:'assets/projects/pajaro-en-piedra.jpg',alt:'Pájaro en Piedra, campaña inmobiliaria para Archipiélago'}]},
  {id:'bajel',name:'Bajel',category:'design',label:'DISEÑO / GASTRONOMÍA',cover:'assets/projects/bajel-chef-story.jpg',tone:'bajel',description:'Una invitación a la mesa. Story para una cena con el chef invitado Mario Papa, con una dirección visual centrada en la experiencia gastronómica.',media:[{src:'assets/projects/bajel-chef-story.jpg',alt:'Story de cena con el chef Mario Papa en Bajel'}]},
  {id:'archipielago-video',name:'Archipiélago en movimiento',category:'video',label:'VIDEO / INMOBILIARIO',cover:'assets/videos/archipielago-indispensables-poster.jpg',tone:'video',description:'Una pieza audiovisual de Archipiélago para descubrir el entorno y sus posibilidades.',media:[{src:'assets/videos/archipielago-indispensables.mp4',type:'video',poster:'assets/videos/archipielago-indispensables-poster.jpg',alt:'Video Archipiélago: indispensables'}]},
  {id:'levels',name:'Levels Dermatology',category:'design',label:'DISEÑO / SKINCARE',cover:'assets/projects/levels-murad.jpg',tone:'levels',description:'Una pieza de producto para presentar Murad Clarifying Booster en la comunicación de Levels Dermatology.',media:[{src:'assets/projects/levels-murad.jpg',alt:'Murad Clarifying Booster para Levels Dermatology'}]},
  {id:'citron',name:'Citrón · Grupo Gia',category:'design',label:'DISEÑO / CAMPAÑA',cover:'assets/projects/citron-grupo-gia.jpg',tone:'citron',description:'Comunicación visual para Citrón de Grupo Gia: inversión sustentable en limón persa en Oxkutzcab, Yucatán, y vida en contacto con la naturaleza.',media:[{src:'assets/projects/citron-grupo-gia.jpg',alt:'Pieza de inversión en limón persa para Citrón de Grupo Gia'},{src:'assets/projects/citron-inversion-sustentable.jpg',alt:'Inversión sustentable en Oxkutzcab, pieza de Citrón de Grupo Gia'}]},
  {id:'picking',name:'Picking Express',category:'design',label:'DISEÑO / SERVICIOS',cover:'assets/projects/picking-express-embalaje.jpg',tone:'picking',description:'Piezas que ponen el servicio a la vista: embalaje personalizado, rastreo desde la recolección hasta la entrega, asesoría en importación y exportación, e identidad de marca.',media:[{src:'assets/projects/picking-express-embalaje.jpg',alt:'Pieza de embalaje personalizado para Picking Express'},{src:'assets/projects/picking-express-somos.jpg',alt:'Pieza #SomosPickingExpress con carga embalada'},{src:'assets/projects/picking-express-rastreo.jpg',alt:'Pieza de rastreo activo de envíos para Picking Express'},{src:'assets/projects/picking-express-asesoria.jpg',alt:'Pieza de asesoría en importación y exportación para Picking Express'}]},
  {id:'alavar',name:'A Lavar',category:'video',label:'VIDEO / COMERCIAL',cover:'assets/videos/a-lavar-sucursal-poster.jpg',tone:'video',description:'Una pieza audiovisual para presentar una sucursal de A Lavar.',media:[{src:'assets/videos/a-lavar-sucursal.mp4',type:'video',poster:'assets/videos/a-lavar-sucursal-poster.jpg',alt:'Video de sucursal A Lavar'}]},
  {id:'mitica',name:'Mítica · Promocional',category:'video',label:'VIDEO / PROMOCIONAL',cover:'assets/videos/mitica-promocional-poster.jpg',tone:'video',description:'Pieza promocional audiovisual del archivo de trabajo de Desruptivo.',media:[{src:'assets/videos/mitica-promocional.mp4',type:'video',poster:'assets/videos/mitica-promocional-poster.jpg',alt:'Video promocional Mítica'}]},
  {id:'recorrido',name:'Recorrido residencial',category:'video',label:'VIDEO / RECORRIDO',cover:'assets/videos/recorrido-residencial-poster.jpg',tone:'video',description:'Un recorrido residencial en formato vertical: espacio, presentación y movimiento.',media:[{src:'assets/videos/recorrido-residencial.mp4',type:'video',poster:'assets/videos/recorrido-residencial-poster.jpg',alt:'Video de recorrido residencial'}]},
  {id:'cuatro-millones',name:'Cuatro millones',category:'video',label:'VIDEO / INMOBILIARIO',cover:'assets/videos/cuatro-millones-poster.jpg',tone:'video',description:'Contenido inmobiliario en formato vertical, con presentación a cámara.',media:[{src:'assets/videos/cuatro-millones.mp4',type:'video',poster:'assets/videos/cuatro-millones-poster.jpg',alt:'Video inmobiliario Cuatro millones'}]}
];
